# .github/workflows/convert-to-pdf.yml

name: Docs to PDF
# This workflow is triggered on pushes to the repository.
on:
  push:
   branches:
     - main
    # Paths can be used to only trigger actions when you have edited certain files, such as a file within the /docs directory
   paths:
     - 'docs/*.md'
     - 'docs/assets/**'

jobs:
  converttopdf:
    name: Build PDF
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: baileyjm02/markdown-to-pdf@v1
        with:
          input_path: docs
          output_dir: docs/pdf
          images_dir: docs/assets
          image_import: ./docs/assets
          build_pdf: true
      - name: Setup Git
        run: |
          git config user.name "GitHub-Actions[Bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - name: Push Changes
        shell: bash
        run: |
          git status
          git add docs/pdf
          git commit -m "[Bot] Upload generated PDF"
          git push origin main
